using Domain.Entities.EmployeeSalary;
using Infrastructure.Repositories.GenericRepository.FullAuditGenericRepository;

namespace Infrastructure.Repositories.BusinessRepository.EmployeeSalary.Interface;

public interface IEmployeeSalaryRepository : IFullAuditGenericRepository<EmployeeSalaryEntity>;